# RepoSweep database setup for local MySQL 8.0
#
# Usage (from repo root):
#   powershell -ExecutionPolicy Bypass -File scripts\setup_db.ps1
#
# This will:
#   1. Ask for the MySQL root password (typed input, not stored)
#   2. Create the `reposweep` database
#   3. Create a dedicated `reposweep` user (default password "reposweep")
#   4. Apply database\schema.sql
#   5. Generate backend\.env with DATABASE_URL + a random SECRET_KEY

param(
    [string]$RootUser = "root",
    [string]$SqlUser = "reposweep",
    [string]$SqlPass = "reposweep",
    [string]$DbName = "reposweep"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

$mysql = "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"
if (-not (Test-Path $mysql)) { $mysql = "mysql" }

$secret = Read-Host "Enter MySQL root password" -AsSecureString
$ptr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secret)
$rootPw = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($ptr)
[System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
if ([string]::IsNullOrEmpty($rootPw)) { throw "Root password is required." }

$env:MYSQL_PWD = $rootPw
try {
    Write-Host "Creating database '$DbName' and user '$SqlUser'..."
    $sql = @"
CREATE DATABASE IF NOT EXISTS ``$DbName`` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$SqlUser'@'localhost' IDENTIFIED BY '$SqlPass';
CREATE USER IF NOT EXISTS '$SqlUser'@'127.0.0.1' IDENTIFIED BY '$SqlPass';
GRANT ALL PRIVILEGES ON ``$DbName``.* TO '$SqlUser'@'localhost';
GRANT ALL PRIVILEGES ON ``$DbName``.* TO '$SqlUser'@'127.0.0.1';
FLUSH PRIVILEGES;
"@
    $sql | & $mysql -u $RootUser > $null
    if ($LASTEXITCODE -ne 0) { throw "Failed to create database/user (exit $LASTEXITCODE)." }

    Write-Host "Applying database/schema.sql..."
    $env:MYSQL_PWD = $SqlPass
    Get-Content -Raw -LiteralPath (Join-Path $root "database\schema.sql") | & $mysql -u $SqlUser $DbName
    if ($LASTEXITCODE -ne 0) { throw "Failed to apply schema (exit $LASTEXITCODE)." }
}
finally {
    Remove-Item Env:\MYSQL_PWD -ErrorAction SilentlyContinue
}

$secretKey = -join ([char[]](48..57 + 65..90 + 97..122) | Get-Random -Count 48 | ForEach-Object { [char]$_ })
$envFile = Join-Path $root "backend\.env"
$envContent = @"
# Generated by scripts/setup_db.ps1
DATABASE_URL=mysql+pymysql://$SqlUser`:$SqlPass`@localhost:3306/${DbName}?charset=utf8mb4
SECRET_KEY=$secretKey
FRONTEND_URL=http://localhost:5173
BACKEND_URL=http://localhost:5000
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
"@
Set-Content -LiteralPath $envFile -Value $envContent -Encoding ascii
Write-Host ""
Write-Host "Done. Database '$DbName' ready and backend\.env written."
Write-Host "Connection string: mysql+pymysql://$SqlUser`:***@localhost:3306/$DbName?charset=utf8mb4"